# Generated by Django 2.2.7 on 2019-12-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False, verbose_name='地址id')),
                ('location', models.CharField(max_length=20, verbose_name='地址')),
                ('address_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('address_tel', models.CharField(max_length=11, verbose_name='手机号')),
                ('sex', models.IntegerField(default=1, verbose_name='性别')),
                ('address_status', models.IntegerField(default=1, verbose_name='地址状态')),
            ],
        ),
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评价ID')),
                ('comment_content', models.CharField(max_length=300, verbose_name='评价内容')),
                ('level', models.IntegerField(default=1, verbose_name='星级评分')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('comment_status', models.IntegerField(default=1, verbose_name='评论状态')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('good_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('good_pic', models.ImageField(default='user_avatar/default.png', upload_to='good_pic/', verbose_name='商家头像')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='商品单价')),
                ('discount', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='折扣')),
                ('good_num', models.IntegerField(default=0, verbose_name='商品库存')),
                ('remark', models.CharField(max_length=200, null=True, verbose_name='商品介绍')),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单详情ID')),
                ('number', models.IntegerField(default=1, verbose_name='数量')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='折扣后单价')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Goods', verbose_name='商品id')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('account', models.CharField(max_length=20, verbose_name='账号')),
                ('pwd', models.CharField(max_length=16, verbose_name='密码')),
                ('user_name', models.CharField(max_length=10, verbose_name='用户名')),
                ('user_tel', models.CharField(max_length=11, verbose_name='手机号')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='用户创建时间')),
                ('user_avatar', models.ImageField(default='userDefault.png', upload_to='user_avatar/', verbose_name='用户头像')),
                ('user_status', models.IntegerField(default=1, verbose_name='用户状态')),
            ],
            options={
                'unique_together': {('account', 'user_tel')},
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商家ID')),
                ('account', models.CharField(max_length=20, verbose_name='商家账号')),
                ('pwd', models.CharField(max_length=16, verbose_name='密码')),
                ('real_name', models.CharField(max_length=5, verbose_name='商家真实姓名')),
                ('identity_card', models.CharField(max_length=18, verbose_name='身份证')),
                ('identity_card_front', models.ImageField(upload_to='stores_identity_card/', verbose_name='商家身份证正面')),
                ('identity_card_back', models.ImageField(upload_to='stores_identity_card/', verbose_name='商家身份证反面')),
                ('store_name', models.CharField(max_length=10, verbose_name='商家名称')),
                ('store_avatar', models.ImageField(default='storeDefault.png', upload_to='store_avatar/', verbose_name='商家头像')),
                ('store_tel', models.CharField(max_length=11, verbose_name='手机号')),
                ('address', models.CharField(max_length=20, verbose_name='商家地址')),
                ('open_time', models.DateTimeField(verbose_name='开店时间')),
                ('close_time', models.DateTimeField(verbose_name='关店时间')),
                ('remark', models.CharField(max_length=200, null=True, verbose_name='商家介绍')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='用户创建时间')),
                ('store_status', models.IntegerField(default=0, verbose_name='商家状态')),
            ],
            options={
                'unique_together': {('account', 'store_tel')},
            },
        ),
        migrations.CreateModel(
            name='Riders',
            fields=[
                ('rider_id', models.AutoField(primary_key=True, serialize=False, verbose_name='骑手ID')),
                ('account', models.CharField(max_length=20, verbose_name='骑手账号')),
                ('pwd', models.CharField(max_length=16, verbose_name='密码')),
                ('rider_name', models.CharField(max_length=5, verbose_name='骑手真实姓名')),
                ('identity_card', models.CharField(max_length=18, verbose_name='身份证')),
                ('identity_card_front', models.ImageField(upload_to='riders_identity_card/', verbose_name='骑手身份证正面')),
                ('identity_card_back', models.ImageField(upload_to='riders_identity_card/', verbose_name='骑手身份证反面')),
                ('rider_tel', models.CharField(max_length=11, verbose_name='手机号')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='用户创建时间')),
                ('rider_status', models.IntegerField(default=1, verbose_name='骑手状态')),
                ('earnmoney', models.FloatField(default=0.0, verbose_name='收益')),
            ],
            options={
                'unique_together': {('account', 'rider_tel')},
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('total_price', models.FloatField(verbose_name='总价')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='完成时间')),
                ('order_status', models.IntegerField(default=0, verbose_name='订单状态')),
                ('comment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Coments', verbose_name='评论id')),
                ('order_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Address', verbose_name='送餐地址id')),
                ('order_detail', models.ManyToManyField(through='app01.Order_details', to='app01.Goods')),
                ('order_rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Riders', verbose_name='骑手id')),
                ('order_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Stores', verbose_name='商家id')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Users', verbose_name='用户id')),
            ],
        ),
        migrations.AddField(
            model_name='order_details',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Orders', verbose_name='订单'),
        ),
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('goodtype_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品类型ID')),
                ('goodtype_name', models.CharField(max_length=10, verbose_name='商品类型名称')),
                ('goodtype_status', models.IntegerField(default=1, verbose_name='商品类型状态')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Stores', verbose_name='商店id')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='good_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Stores', verbose_name='商家'),
        ),
        migrations.AddField(
            model_name='goods',
            name='good_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.GoodType', verbose_name='商品类型'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Users', verbose_name='用户'),
        ),
    ]
