# Generated by Django 2.2.7 on 2019-12-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='good_name',
            field=models.CharField(default=1, max_length=15, verbose_name='商品名称'),
            preserve_default=False,
        ),
    ]
