# Generated by Django 2.2.7 on 2019-12-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_goods_good_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='identity_card_back',
            field=models.ImageField(null=True, upload_to='stores_identity_card/', verbose_name='商家身份证反面'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='identity_card_front',
            field=models.ImageField(null=True, upload_to='stores_identity_card/', verbose_name='商家身份证正面'),
        ),
    ]
