# Generated by Django 2.2.7 on 2019-12-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20191204_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='identity_card',
            field=models.CharField(max_length=18, null=True, verbose_name='身份证'),
        ),
    ]
