# Generated by Django 2.2.7 on 2019-12-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20191204_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='close_time',
            field=models.TimeField(verbose_name='关店时间'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='open_time',
            field=models.TimeField(verbose_name='开店时间'),
        ),
    ]
