# Generated by Django 2.2.7 on 2019-12-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20191204_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='discount',
            field=models.FloatField(default=1.0, verbose_name='折扣'),
        ),
    ]
