# Generated by Django 2.2.7 on 2019-12-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20191204_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='discount',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='折扣'),
        ),
    ]
