# Generated by Django 2.2.7 on 2019-12-06 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20191206_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Riders', verbose_name='骑手id'),
        ),
    ]
